### ISSUE TITLE
getting error while running train.py in windows 

### ISSUE THREAD

**Issue by hgoyal194** [tucan9389/tf2-mobile-pose-estimation#68]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Harsh\anaconda3\envs\posewin\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = main(fd)
  File "C:\Users\Harsh\anaconda3\envs\posewin\lib\multiprocessing\spawn.py", line 114, in main
    prepare(preparation_data)
  File "C:\Users\Harsh\anaconda3\envs\posewin\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Harsh\anaconda3\envs\posewin\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main")
  File "C:\Users\Harsh\anaconda3\envs\posewin\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Harsh\anaconda3\envs\posewin\lib\runpy.py", line 96, in run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Harsh\anaconda3\envs\posewin\lib\runpy.py", line 85, in run_code
    exec(code, run_globals)
  File "C:\Users\Harsh\Desktop\tf2-mobile\train.py", line 135, in <module>
    from evaluate import calculate_total_pckh
  File "C:\Users\Harsh\Desktop\tf2-mobile\evaluate.py", line 105, in <module>
    manager = multiprocessing.Manager()
  File "C:\Users\Harsh\anaconda3\envs\posewin\lib\multiprocessing\context.py", line 56, in Manager
    m.start()
  File "C:\Users\Harsh\anaconda3\envs\posewin\lib\multiprocessing\managers.py", line 563, in start
    self._process.start()
  File "C:\Users\Harsh\anaconda3\envs\posewin\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\Harsh\anaconda3\envs\posewin\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Harsh\anaconda3\envs\posewin\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Harsh\anaconda3\envs\posewin\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Harsh\anaconda3\envs\posewin\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

    This probably means that you are not using fork to start your
    child processes and you have forgotten to use the proper idiom
    in the main module:

        if __name__ == '__main__':
            freeze_support()
            ...

    The "freeze_support()" line can be omitted if the program
    is not going to be frozen to produce an executable.
```

Please help me to solve this.

**Comment by hgoyal194** [comment]
I havn't changed anything in train.py file
